clc;
close all;
clear all;
f1=input('Enter the frequency of carrier wave');
f2=input('Enter frequency of pulse');
A=3;
t=0:0.001:1;
x=A.*sin(2*pi*f1*t);
u=A.*square(2*pi*f2*t);
v=x.*u;
subplot(3,1,1);
plot(t,x);
xlabel('time');
ylabel('amplitude');
title('Carrier-signal/Prabesh/55');
grid on;
subplot(3,1,2);
plot(t,u);
xlabel('time');
ylabel('amplitude');
title('Message-wave/Prabesh/55');
grid on;
subplot(3,1,3);
plot(t,v);
xlabel('time');
ylabel('amplitude');
title('Phase Shift Key/Prabesh/55');
grid on;