clc;
close all;
clear all;
fc=input('Enter the frequency of carrier wave');
fp=input('Enter frequency of pulse');
amp=input('Enter amplitude');
t=0:0.001:1;
m=amp/2.*square(2*pi*fp*t)+(amp/2);
c=amp.*sin(2*pi*fc*t);
w=c.*m;
subplot(3,1,1);
plot(t,m);
xlabel('time');
ylabel('amplitude');
title('Message-pulse/Prabesh/55');
legend('message signal m(t)');
grid on;
subplot(3,1,2);
plot(t,c);
xlabel('time');
ylabel('amplitude');
title('Carrier-wave/Prabesh/55');
legend('carrier signal m(t)');
grid on;
subplot(3,1,3);
plot(t,w);
xlabel('time');
ylabel('amplitude');
title('Amplitude Shift Key/Prabesh/55');
legend('ASK signal m(t)');
grid on;