clc;
close all;
clear all;
t=0:0.001:1;
fm=input('Enter message frequency');
am=input('Enter message amplitude');
fc=input('Enter carrier frequency');
ac=input('Enter carrier amplitude');
m=am*sin(2*pi*fm*t);
c=ac*sin(2*pi*fc*t);
x=m.*c;
mod=x+(ac.*c);
subplot(311);
plot(t,m);
xlabel('time');
ylabel('amplitude');
title('Message-signal/Nitesh/52');
grid on;
subplot(312);
plot(t,c);
xlabel('time');
ylabel('amplitude');
title('Carrier-signal/Nitesh/52');
grid on;
subplot(313);
plot(t,mod);
xlabel('time');
ylabel('amplitude');
title('Amplitude over-modulation/Nitesh/52');
grid on;